### ISSUE TITLE
Problem installing on Ironwood

### ISSUE THREAD

**Issue by ahmed23e** [appsembler/xblock-video#31]
**Hi
When I try to install xblock-video on ironwood release I get this error**

> Obtaining video_xblock from git+https://github.com/appsembler/xblock-video.git#egg=video_xblock
> Updating ./venvs/edxapp/src/video-xblock clone
> DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
> Requirement already satisfied: XBlock<2.0.0,>=0.4.10 in ./venvs/edxapp/lib/python2.7/site-packages (from video_xblock)
> Collecting xblock-utils<=1.0.5,>=1.0.2 (from video_xblock)
> Could not find a version that satisfies the requirement xblock-utils<=1.0.5,>=1.0.2 (from video_xblock) (from versions: 1.2.0, 1.2.1, 1.2.2)
> No matching distribution found for xblock-utils<=1.0.5,>=1.0.2 (from video_xblock)
> You are using pip version 9.0.3, however version 19.2.2 is available.
> You should consider upgrading via the ‘pip install --upgrade pip’ command.

**Comment by lhwong** [comment]
I face the same issue.

**Comment by Millz0r** [comment]
I've tested it with Ironwood and xblock-utils==1.2.0 and it seems to work fine.

To install, you must remove these dependencies from setup.py file (line 57):

        'xblock-utils>=1.0.2,<=1.0.5',
        'pycaption>=0.7.1,<1.0',  # The latest Python 2.7 compatible version

Also change the xblock-utils version in requirements.txt to 1.2.0.

Then, pip install the xblock-video from your modified source. After the installation remember to rebuild your assets using paver, before restarting and enabling the module in the CMS.

**Comment by duraiganesh0** [comment]
hi @Millz0r  i followed your instructions but I'm getting this new error
`File "/edx/app/edxapp/edx-platform/manage.py", line 120, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 19, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/venvs/edxapp/src/edx-jsme/edx_jsme/__init__.py", line 7, in <module>
    from capa import inputtypes, responsetypes
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/responsetypes.py", line 33, in <module>
    from lxml.html.soupparser import fromstring as fromstring_bs  # uses Beautiful Soup!!! FIXME?
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/lxml/html/soupparser.py", line 10, in <module>
    from bs4 import (
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'`

DO YOU HAVE ANY IDEA??

**Comment by duraiganesh0** [comment]
hey @Millz0r fixed the above issue. but still getting an error. here is the log. Did you install it in ironwood?? please provide some details here. I'm stuck on this for the past 1 week

`2021-06-07 04:03:19,571 WARNING 1573 [xblock.plugin] plugin.py:149 - Unable to load XBlock 'video_xblock'
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log Traceback (most recent call last):
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/plugin.py", line 146, in load_classes
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log     yield (class_.name, cls._load_class_entry_point(class_))
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/plugin.py", line 75, in _load_class_entry_point
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log     class_ = entry_point.load()
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2442, in load
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log     self.require(*args, **kwargs)
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2465, in require
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log     items = working_set.resolve(reqs, env, installer, extras=self.extras)
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log     raise VersionConflict(dist, req).with_context(dependent_req)
Jun 06 23:33:19 xenops-stg-edxapp-ip-10-1-11-228 cms-stderr.log ContextualVersionConflict: (beautifulsoup4 4.7.1 (/edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages), Requirement.parse('beautifulsoup4<4.5.0,>=4.2.1'),`
