### ISSUE TITLE
Problem with Vimeo on Hawthorn release

### ISSUE THREAD

**Issue by jramnai** [appsembler/xblock-video#32]
I've used [this tweak](https://github.com/appsembler/xblock-video/issues/31#issuecomment-569813556) and installed the xblock but when I update assets I' m getting this error:

`Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/plugin.py", line 146, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/plugin.py", line 75, in _load_class_entry_point
    class_ = entry_point.load()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (beautifulsoup4 4.6.0 (/edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages), Requirement.parse('beautifulsoup4<4.5.0,>=4.2.1'), set(['pycaption']))`

**Comment by duraiganesh0** [comment]
hey @jramnai  did you fix this issue? can you provide an update please?
